### ISSUE TITLE
z/VM IPL of z/OS fails with disabled wait PSW 00020000 80000000 00000000 0000108A

### ISSUE THREAD

**Issue by moshix** [Fish-Git/hyperion#105]
With z/VM 5.3 and all Hercules 4.00 versions (including the SDL Hyperion), 3 times out of 4 when I IPL z/OS either in 31bit or 64bit version, I get this CPU wait state:

`00: HCPGIR450W CP entered; disabled wait PSW 00020000 80000000 00000000 0000108A`

If I reduce the memory allocated to Hercules to under 2GB then the wait states happen less often. If I give Hercules (and therefore z/VM), say 10GB of RAM, then the wait states happen virtually all of the time. 

The problem does _not_ happen with VM/ESA guest machines nor with VSE guest machines.

I tried both single CPU (given the wait state code) as well as multi processor guest machines, but it did not help. The same exact behavior resulted.

Any idea what I am doing wrong?

thanks

**Comment by Fish-Git** [comment]
> Any idea what I am doing wrong?

Nothing.

When I originally had z/VM 5.3 myself (I no longer have it) I noticed the _exact_ same thing. My own resolution was to simply run Hercules with _less_ than 2GB of `MAINSIZE` (e.g. `1600M` instead) and give my z/OS guest even less than that (e.g. only 1GB).

I believe the problem is in z/VM 5.3 itself and not Hercules. The problem does not occur in later releases of z/VM (e.g. z/VM 6.3).
