### ISSUE TITLE
Error HHC01530E when MODPATH with blanks is used

### ISSUE THREAD

**Issue by YossiReichman** [Fish-Git/hyperion#109]
In my configuration file I have:
```
MODPATH      C:\My Hercules\My modpath dir
```
which causes error `HHC01530E` to be issued:
```
HHC01530E HDL: usage: MODPATH <path>
HHC01441E Config file[36] C:/Users/Fish/HercGUI/Configuration Files/__MIN.cnf.txt: error processing statement: MODPATH C:\My Hercules\My modpath dir
```
&nbsp;
Entering the command "`help modpath`" does not provide any clues:
```
HHC01603I help modpath
HHC01603I 
HHC01602I Command               Description
HHC01602I ----------------      -------------------------------------------------------
HHC01602I modpath               Set module load path
HHC01603I 
```
&nbsp;
The documentation for the `MODPATH` statement says:
> Specifies the path where dynamic modules are loaded from. When a modpath statement is specified, the path on the modpath statement is searched before the default path is searched. When a relative path is specified is interpreted as a relative path within the default search path, if an absolute path is specified is interpreted as such.
>
> The default MODPATH is hercules, which means modules are loaded from the directory hercules within the default LD_LIBRARY_PATH.

Which doesn't provide very much help either.

**Comment by Fish-Git** [comment]
Hi Joe!

Your problem is twofold:

1. If your MODPATH directory contains any blanks, you need to surround it within quotes.
2. The MODPATH statement expects only a single directory specification, not multiple directories.

The MODPATH statement is _not_ the same as the PATH (or LIB or INCLUDE, etc) environment variable. It does _not_ specify multiple search directories separated by semicolons.

The MODPATH statement defines only a **_single_** directory, which must be enclosed within double quotes if it contains any blanks, e.g:
```
MODPATH      "C:\My Hercules\My modpath dir"
```
I apologize for the unhelpful "help" display and the unclear documentation. I have committed an update to both which I hope makes things a little more clear.

Thank you for reporting this.
