### ISSUE TITLE
FWPCUtil not found

### ISSUE THREAD

**Issue by YossiReichman** [Fish-Git/hyperion#118]
A friend of mine has the modpath set to c:\trail all the CTCI exe and dll's are there tuntap is loaded from that directory however FWPCUtil which resides in that directory as well get dialog box message that its not found 

thanks

**Comment by Fish-Git** [comment]
is c:\trial in your path?

**Comment by YossiReichman** [comment]
no; Its a random directory Where CTCTI-WIN Fish Lib modules were placed

thanks

**Comment by Fish-Git** [comment]
Hmmm... So you never actually _installed_ CTCI-WIN on this system, correct? All you did was manually copy over the binaries, am I right?

(sigh) Joe, you should know better.&nbsp;`:(`

If you would do a proper _install_ of CTCI-WIN on this system (instead of manually copying binaries all over the place), then a `modpath` statement would not be necessary and things would just work!

Have you _tried_ adding that directory to your Windows PATH?? The `modpath` statement tells Hercules where to load the CTCI modules (DLLs) from, but the CTCI modules themselves need to run `FWPCUtil.exe` to retrieve WinPCap information, and they purposely do _not_ presume it exists in the same directory.  They just do a `CreateProcess` and expect the operating system to locate the executable they're trying to run by searching the directories defined in the PATH variable.

Try adding that directory to your PATH variable and see if that helps any.

Otherwise, I **_strongly suggest_** you stop manually copying binaries from one system to another and actually do an official **_install_** of the product instead!

**Comment by YossiReichman** [comment]
I think fish wanted to know if it was in %% path %%

Joe Reichman
170-10 73 rd ave 
Fresh meadows NY 11366

**Comment by Fish-Git** [comment]
@YossiReichman 

Joe, has this issue been resolved for you?  I would like to close it.

(p.s. was your previous comment, with your address, meant for someone else? Should I delete it?)

**Comment by YossiReichman** [comment]
Yes

Joe Reichman
170-10 73 rd ave 
Fresh meadows NY 11366

**Comment by Fish-Git** [comment]
Thanks, Joe. I will close the issue.
